name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_container:
    runs-on: ubuntu-latest

    steps:
    - name: Pull Docker Image
      run: docker pull cjgruenke/text-analyzer:latest

    - name: Run Tests in Container
      run: docker run cjgruenke/text-analyzer:latest
